## 1D eisum operations

| subscripts | numpy | Description |
| :--- | :--- | :--- |
|`('i', A)`|`A`|returns a view of A|
|`('i->', A)`|`sum(A)`|	sums the values of A|
|`('i,i->i', A, B)`|`A * B`|element-wise multiplication of A and B|
|`('i,i', A, B)`|`inner(A, B)`|inner product of A and B|
|`('i,j->ij', A, B)`|`outer(A, B)`|outer product of A and B|

In [2]:
import numpy as np
a=np.array([1,2,3])
np.einsum('i',a)

array([1, 2, 3])

In [3]:
np.einsum('i->',a)

6

In [5]:
a=np.array([1,2,3])
np.einsum('i,i->i',a,b)

array([ 2,  6, 12])

In [14]:
a=np.array([1/np.sqrt(2),1/np.sqrt(2)])
b=np.array([1/np.sqrt(2),1/np.sqrt(2)])
np.dot(a,b)

0.9999999999999998

In [16]:
np.einsum('i,i',a,b)

0.9999999999999998

In [19]:
a=np.array([1,2,3])
b=np.array([2,3,4])
np.einsum('i,j->ij',a,b)

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

## 2D eisum operations

| subscripts | numpy | Description |
| :--- | :--- | :--- |
|`('ij', A)`|`A`|	returns a view of A|
|`('ji', A)`|`A.T`|	view transpose of A|
|`('ii->i', A)`|`diag(A)`|view main diagonal of A|
|`('ii', A)`|`trace(A)`|sums main diagonal of A|
|`('ij->', A)`|`sum(A)`|sums the values of A|
|`('ij->j', A)`|`sum(A, axis=0)`|sum down the columns of A (across rows)|
|`('ij->i', A)`|`sum(A, axis=1)`|sum horizontally along the rows of A|
|`('ij,ij->ij', A, B)`|`A * B`|element-wise multiplication of A and B|
|`('ij,ji->ij', A, B)`|`A * B.T`|element-wise multiplication of A and B.T|
|`('ij,jk', A, B)`|`dot(A, B)`|	matrix multiplication of A and B|
|`('ij,kj->ik', A, B)`|`inner(A, B)`|	inner product of A and B|
|`('ij,kj->ikj', A, B)`|`A[:, None] * B`|each row of A multiplied by B|
|`('ij,kl->ijkl', A, B)`|`A[:, :, None, None] * B`|	each value of A multiplied by B|

In [20]:
a=np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
#('ij', A)	A	returns a view of A
np.einsum('ij', a)

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
#('ji', A)	A.T	view transpose of A
np.einsum('ji', a)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [31]:
#('ii->i', A)	diag(A)	view main diagonal of A
a=np.array([[1,2,3],[1,3,4],[3,4,5]])
a

array([[1, 2, 3],
       [1, 3, 4],
       [3, 4, 5]])

In [32]:
np.einsum('ii->i', a)

array([1, 3, 5])

In [33]:
#('ii', A)	trace(A)	sums main diagonal of A
np.einsum('ii', a)

9

In [34]:
#('ij->', A)	sum(A)	sums the values of A
np.einsum('ij->', a)

26

In [35]:
#('ij->j', A)	sum(A, axis=0)	sum down the columns of A (across rows)
np.einsum('ij->j', a)

array([ 5,  9, 12])

In [36]:
#('ij->i', A)	sum(A, axis=1)	sum horizontally along the rows of A
np.einsum('ij->i', a)

array([ 6,  8, 12])

In [41]:
#('ij,ij->ij', A, B)	A * B	element-wise multiplication of A and B
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [42]:
np.einsum('ij,ij->ij', a,b)

array([[ 5, 12],
       [21, 32]])

In [43]:
#('ij,ji->ij', A, B)	A * B.T	element-wise multiplication of A and B.T
np.einsum('ij,ji->ij', a,b)

array([[ 5, 14],
       [18, 32]])

In [45]:
#('ij,jk', A, B)	dot(A, B)	matrix multiplication of A and B
np.einsum('ij,ji->', a,b)

69

In [46]:
#('ij,kj->ik', A, B)	inner(A, B)	inner product of A and B
np.einsum('ij,kj->ik', a,b)

array([[17, 23],
       [39, 53]])

In [ ]:
#('ij,kj->ikj', A, B)	A[:, None] * B	each row of A multiplied by B


In [ ]:
#('ij,kl->ijkl', A, B)	A[:, :, None, None] * B